spring.application.name=techcup-futbol
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs
spring.datasource.url=jdbc:postgresql://localhost:5432/techcup
spring.datasource.username=TECHCUP_DOSW
spring.datasource.password=LosAsgardianos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


