server:
  port: 8080

spring:
  application:
    name: techcup-futbol
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

springdoc:
  swagger-ui:
    path: /api-docs

logging:
  level:
    root: INFO
    com.techcup.techcup_futbol: DEBUG
    org.springframework: INFO
    org.hibernate: WARN
  file:
    name: logs/techcup.log

jwt:
  secret: "TechCupFutbol2026ClaveSecretaMuyLargaParaQueSean256BitsMinimo!!"
  expiration-ms: 86400000